### ISSUE TITLE
Seems like itunes changed how the Scaling control works, here's the fix.

### ISSUE THREAD

**Issue by Hotcooler** [bendodson/itunes-artwork-finder#1]
Line 50 of api.php change this `$hires = str_replace('.100x100-75', '', $result->artworkUrl100);` into something like this `$hires = str_replace('100x100bb-85', '2100x2100bb-92', $result->artworkUrl100);` to get 2100x1400 jpeg with 92 quality.

Where 2100x2100 is the resolution, "bb" some sort of separator and 92 is jpeg quality.

**Comment by bendodson** [comment]
Thanks for the fix - much appreciated!

**Comment by xrTor** [comment]
thank you!
