### ISSUE TITLE
Licensing of this project

### ISSUE THREAD

**Issue by jonasmusall** [bendodson/itunes-artwork-finder#13]
Is the source code in this repo licensed in some way? Am I free to use, adapt and publish it myself?

I used it to write a command line app in C# which searches for and downloads album cover artwork and I would like to publish the source of that on GH. Additionally, I am thinking about writing a version which does not need a server backend and can be used with static site hosts like GH Pages.

PS.: Thank you for making the source code of this awesome project publicly available, and for hosting an instance of it. Way better than searching Google Images for high res artworks :)

**Comment by bendodson** [comment]
Good catch! I've added a license to the project now (TL;DR - it's The Unlicense so you can do what you want with the code)
