### ISSUE TITLE
Add movie collections

### ISSUE THREAD

**Issue by NicolaIsotta** [bendodson/itunes-artwork-finder#4]
First of all, thanks for the tool. It has been really useful.
Would it be possible to add movie collections? Using `Movie` or `Apple ID (Movie)` doesn't work.
[Example link](https://itunes.apple.com/it/movie-collection/harry-potter-collezione-completa/id1066940040)

**Comment by bendodson** [comment]
First of all, sorry this is a bit of a slow reply 🤣

This appears to be working with the `Apple ID (Movie)` setting. With the [link you provided](https://itunes.apple.com/it/movie-collection/harry-potter-collezione-completa/id1066940040) you'd use id `1066940040` with the artwork finder set to `Apple ID (Movie)` and the country set to `Italy`. That gives the following file:


![](https://is5-ssl.mzstatic.com/image/thumb/Music114/v4/79/64/86/7964868f-39b0-2508-986c-629e9f38b752/HP8Film_DarkArts_V_DD_KA_TT_CVRART_2000x3000_300dpi_IT.lsr/600x600bb.jpg)

If you want to get the artwork for each film within the collection, you do the exact same thing but using the id found in the link to each film i.e. for the Prisoner of Azkaban you'd use `285825306` and you'd get the following:


![](https://is5-ssl.mzstatic.com/image/thumb/Video112/v4/a3/8a/82/a38a82f5-45ec-6cbb-16b8-fcad65d6884c/pr_source.lsr/600x600bb.jpg)
