### ISSUE TITLE
adding download="" and title=""

### ISSUE THREAD

**Issue by xrTor** [bendodson/itunes-artwork-finder#5]
you sould add / title="" / with the $string that added into / alt="" /, it working fine in the api and showing tolltip whaen mousehover on the pictrue, also can add / download="" / on the links xor image, the image xor the link will be downloaded with the name instead the resolution (chrome does support downloading with name accurately). the download tag been added to the end of the 'a'

also i suggest adding the html in description to a 'html' file inside the master #

**Comment by bendodson** [comment]
Sorry this reply was a bit slow 🤣

I have added both suggestions - thanks!
