### ISSUE TITLE
Explanation of `100000x100000-999`?

### ISSUE THREAD

**Issue by csandman** [bendodson/itunes-artwork-finder#7]
I was trying to understand how your code works for the hi-res version of the album artwork, specifically this line:

```php
str_replace('100x100bb', '100000x100000-999', $result->artworkUrl100);
```

And I'm curious why you have the `-999` at the end of the url.  Is there some structure of the URL you figured out?  I tested it out with a few different formats (a `bb` suffix, or no suffix at all) and they seem to have varying results depending on the image I'm looking at.  However, the URL you have seems to work more consistently than most of them.

I assume the actual NxN is irrelevant, it just needs to be larger than the largest res version of the image they have, but the suffix part is what I'm the most curious about.

Also, thanks for this project, I just found it yesterday and its been a great help for a project I've been working on to automatically merge audiobooks into m4b files with the goal of having the best possible metadata.  The artwork from the iTunes API has a far better resolution than Audible.

**Comment by bendodson** [comment]
I can't fully remember the reason but I'm pretty sure it was a quality parameter for the JPEG compression. -100 is probably the maximum thinking about it now but the -999 likely forces it to be the maximum quality.
